/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoMusicBrand;

import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;

//menos este: que serve para mostra uma tela de mensagem na tela
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; //para a tabela

/**
 *
 * @author jojoj
 */
public class Estoque extends javax.swing.JFrame {

    public Connection con;
    public Statement st; // variavel que irá realizar os comandos do BD.
    public ResultSet resultado = null;
    public ResultSet resultado2 = null;
    DefaultTableModel table2;

    public Estoque() {
        initComponents();
        // Conectar com o banco de dados: 

        try { // tenta executar este comando
            con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/XWCLbDUMdi", "XWCLbDUMdi", "aHScI8izn4"); //conectar ao bando de dados turmaa
            st = (Statement) con.createStatement(); // irá guardar os comandos de bando de dados nesta variavel e vai entender os comandos

        } catch (Exception e) { // se der erro, executa este comando.
            JOptionPane.showMessageDialog(null, "Não conectado!");// chama este import para aparecer uma mensagem

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1300, 840));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 830));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 48, 39));
        jLabel1.setText("ESTOQUE");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(248, 146, 17));
        jButton2.setText("Limpar");
        jButton2.setToolTipText("Limpar campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(248, 146, 17));
        jButton4.setText("Retornar");
        jButton4.setToolTipText("Retornar ao menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome", "Categoria", "Tipo", "Marca", "Cor", "Fornecedor", "Quantidade", "Valor de Compra", "Valor de Venda"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jButton3.setBackground(new java.awt.Color(248, 146, 17));
        jButton3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pesquisar");
        jButton3.setToolTipText("Pesquisar Estoque");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Sanfona.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cód. Produto");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Categoria:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));

        jComboBox1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a categoria", "Áudio Profissional", "Bateria & Percussão", "Cordas & Acessórios", "Pianos & Teclados", "Sopro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)))))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addGap(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void limpaDados() {
        // Limpa todos os campos:
        jTextField1.setText("");
        jComboBox1.setSelectedItem("Selecione a categoria");
        jComboBox2.setSelectedItem("Selecione o tipo");

        table2 = (DefaultTableModel) jTable2.getModel();
        table2.setRowCount(0); // apaga todas as celulas da tabela
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Pesquisa os produtos:    
        try {
            String pesquisaEstoque = "Select * from produto;";
            resultado2 = st.executeQuery(pesquisaEstoque); // executa a variavel com os comandos do BD

            while (resultado2.next()) {
                table2 = (DefaultTableModel) jTable2.getModel();
                Object[] dados = {resultado2.getString("cod_instrumento"), resultado2.getString("nome"), resultado2.getString("categoria"),
                    resultado2.getString("tp_instrumento"), resultado2.getString("marca"), resultado2.getString("cor"), resultado2.getString("fornecedor"),
                    resultado2.getString("qtd"), resultado2.getString("valor_compra"), resultado2.getString("valor_venda")};
                table2.addRow(dados);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //limpa todos os campos:
        limpaDados();

    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Retornar a tela principal:
        TelaPrincipalMB principal = new TelaPrincipalMB();

        principal.setVisible(true); // retorna a tela principal

        dispose(); // fecha a tela de estoque
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //A combobox de tipo fica dependente da combobox de categoria:
        if (jComboBox1.getSelectedItem().equals("Áudio Profissional")) {

            jComboBox2.removeAllItems();
            jComboBox1.setSelectedItem("Audio Profissional");

            jComboBox2.addItem("Selecione o tipo");
            jComboBox2.addItem("Acessórios");
            jComboBox2.addItem("Cabos");
            jComboBox2.addItem("Caixas Acusticas");
            jComboBox2.addItem("Fones de Ouvido");
            jComboBox2.addItem("Microfones");
            jComboBox2.addItem("Mixers e Mesas");
            jComboBox2.addItem("Processadores");
            jComboBox2.addItem("Sistema sem Fio");
            jComboBox2.addItem("Tecnologia");

        } else if (jComboBox1.getSelectedItem().equals("Bateria & Percussão")) {

            jComboBox2.removeAllItems();
            jComboBox1.setSelectedItem("Bateria & Percussão");

            jComboBox2.addItem("Selecione o tipo");
            jComboBox2.addItem("Acessórios");
            jComboBox2.addItem("Bateria Acústica");
            jComboBox2.addItem("Bateria Eletrônica");
            jComboBox2.addItem("Ferragens");
            jComboBox2.addItem("Peles");
            jComboBox2.addItem("Percussão");
            jComboBox2.addItem("Kit de Pratos");

        } else if (jComboBox1.getSelectedItem().equals("Cordas & Acessórios")) {

            jComboBox2.removeAllItems();
            jComboBox1.setSelectedItem("Cordas & Acessórios");

            jComboBox2.addItem("Selecione o tipo");
            jComboBox2.addItem("Acessórios");
            jComboBox2.addItem("Amplificadores para Baixo");
            jComboBox2.addItem("Amplificadores para Guitarra");
            jComboBox2.addItem("Bandolim");
            jComboBox2.addItem("Cases");
            jComboBox2.addItem("Cavaco & Banjo");
            jComboBox2.addItem("Contrabaixo");
            jComboBox2.addItem("Controladores & Footswitch");
            jComboBox2.addItem("Efeitos");
            jComboBox2.addItem("Encordoamento");
            jComboBox2.addItem("Guitarra");
            jComboBox2.addItem("Palhetas e Dedeiras");
            jComboBox2.addItem("Peças e Reposições");
            jComboBox2.addItem("Pedal de efeito");
            jComboBox2.addItem("Pedaleira & Multi Efeito");
            jComboBox2.addItem("Ukulele");
            jComboBox2.addItem("Viola Caipira");
            jComboBox2.addItem("Violão Acústico");
            jComboBox2.addItem("Violão Eletroacústico");
            jComboBox2.addItem("Violino");
            jComboBox2.addItem("Violoncello");
        } else if (jComboBox1.getSelectedItem().equals("Pianos & Teclados")) {

            jComboBox2.removeAllItems();
            jComboBox1.setSelectedItem("Pianos & Teclados");

            jComboBox2.addItem("Selecione o tipo");
            jComboBox2.addItem("Acessórios");
            jComboBox2.addItem("Acordeons");
            jComboBox2.addItem("Amplificadores");
            jComboBox2.addItem("Arranjadores");
            jComboBox2.addItem("Controladores");
            jComboBox2.addItem("Pianos");
            jComboBox2.addItem("Synths");
            jComboBox2.addItem("Teclados");
            jComboBox2.addItem("WorkStations");

        } else if (jComboBox1.getSelectedItem().equals("Sopro")) {

            jComboBox2.removeAllItems();
            jComboBox1.setSelectedItem("Sopro");

            jComboBox2.addItem("Selecione o tipo");
            jComboBox2.addItem("Acessórios");
            jComboBox2.addItem("Clarinetas");
            jComboBox2.addItem("Flautas");
            jComboBox2.addItem("Gaitas");
            jComboBox2.addItem("Geral");
            jComboBox2.addItem("Saxofone");
            jComboBox2.addItem("Trompete");

        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // Pesquisa os produtos pelos códigos:        
        try {

            String pesquisaCodigo = "Select categoria, tp_instrumento, cod_instrumento, nome, marca, cor, fornecedor,"
                    + " qtd, valor_compra, valor_venda from produto where cod_instrumento= " + jTextField1.getText();
            resultado = st.executeQuery(pesquisaCodigo); // executa a variavel com os comandos do BD

            limpaDados();
            while (resultado.next()) { // se tiver valor
                jComboBox1.setSelectedItem(resultado.getString("categoria"));
                jComboBox2.setSelectedItem(resultado.getString("tp_instrumento"));

                table2 = (DefaultTableModel) jTable2.getModel();
                Object[] dados = {resultado.getString("cod_instrumento"), resultado.getString("nome"), resultado.getString("categoria"),
                    resultado.getString("tp_instrumento"), resultado.getString("marca"), resultado.getString("cor"), resultado.getString("fornecedor"),
                    resultado.getString("qtd"), resultado.getString("valor_compra"), resultado.getString("valor_venda")};
                table2.addRow(dados);
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
