/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoMusicBrand;

//pacotes para se utilizar no bando de dados:
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;

//menos este: que serve para mostra uma tela de mensagem na tela
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; // para a tabela

public class Venda extends javax.swing.JFrame {

    public Connection con;
    public Statement st; // variavel que irá realizar os comandos do BD.
    public ResultSet resultado = null;

    public DefaultTableModel table2;

    public Venda() {
        initComponents();

        // Conectar com o banco de dados: 
        try { // tenta executar este comando
            con = DriverManager.getConnection("jdbc:mysql://remotemysql.com:3306/XWCLbDUMdi", "XWCLbDUMdi", "aHScI8izn4"); //conectar ao bando de dados turmaa
            st = (Statement) con.createStatement(); // irá guardar os comandos de bando de dados nesta variavel e vai entender os comandos

        } catch (Exception e) { // se der erro, executa este comando.
            JOptionPane.showMessageDialog(null, "Não conectado!");// chama este import para aparecer uma mensagem

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1300, 1150));
        setSize(new java.awt.Dimension(1300, 1150));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 940));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 48, 39));
        jLabel1.setText("VENDA");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField6MouseEntered(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(248, 146, 17));
        jButton3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Pesquisar");
        jButton3.setToolTipText("Pesquisar Venda");
        jButton3.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(248, 146, 17));
        jButton4.setText("Limpar");
        jButton4.setToolTipText("Excluir Venda");
        jButton4.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable2 = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex, int colIndex){
                return false;
            }
        };
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome Produto", "Valor", "Quantidade", "Subtotal", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jComboBox2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a categoria", "Áudio Profissional", "Bateria & Percussão", "Cordas & Acessórios", "Pianos & Teclados", "Sopro" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", " " }));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(248, 146, 17));
        jButton5.setText("Retornar");
        jButton5.setToolTipText("Retornar ao menu");
        jButton5.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Violino.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(230, 180));

        jComboBox4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a marca", "Behringer", "Behringer Instruments", "Blackstar", "Casio", "Comica", "Eagle", "Epiphone", "Fender", "Gator", "Giannini", "Gretsch", "Hering", "Jackson", "Kalani", "Korg", "Luen", "Martin", "Nektar", "On-stage Stands", "Pearl", "PHX", "Roland", "Rozini", "Sennheiser", "Sigma", "SKB", "Soft Case", "Squier By Fender", "Tagima", "Waldman", "Winner", "Yamaha", "Zeus", " " }));

        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a cor", "Azul", "Branco", "Colorido", "Cromado", "Dourado", "Jacarandá", "Louro Preto", "Madeira", "madeira", "Marrom", "Natural", "Prata/Cromado", "Preto", "Preto/Branco", "Preto/Vermelho", "Pérola", "Sem cor", "Vermelho", " ", " ", " ", " " }));

        jComboBox6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a forma de pagamento", "Cartão de Crédito", "Cartão de Débito", "Dinheiro", "PIX" }));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cód. Produto:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel4.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CPF/CNPJ:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel11.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nome do Cliente:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel3.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Categoria:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel5.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tipo:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel7.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Nome do Produto:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel6.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Marca:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel8.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cor:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel9.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Quantidade:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel10.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Forma de Pagamento:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel12.setPreferredSize(new java.awt.Dimension(160, 25));

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Valor do Produto:");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 146, 17)));
        jLabel14.setPreferredSize(new java.awt.Dimension(160, 25));

        jButton1.setBackground(new java.awt.Color(248, 146, 17));
        jButton1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.setToolTipText("Registrar Venda");
        jButton1.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(248, 146, 17));
        jButton2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Incluir");
        jButton2.setToolTipText("Incluir mais uma venda");
        jButton2.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField9)
                                    .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1))
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField11)))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1157, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1168, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost

    }//GEN-LAST:event_jPanel1FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Adiciona mais um produto a venda e diminui o estoque:

        int cod_instrumento = Integer.valueOf(jTextField2.getText());

        try {
            String pesquisaQtd = "select qtd from produto where cod_instrumento= " + cod_instrumento + ";";
            resultado = st.executeQuery(pesquisaQtd);

            if (resultado.next()) {
                String qtdProduto = resultado.getString("qtd");

                int qtd_estoque = Integer.valueOf(qtdProduto);
                int qtd_ProdutoVenda = Integer.valueOf(jTextField9.getText());

                if (qtd_estoque > 0) {
                    if (qtd_ProdutoVenda <= qtd_estoque) {

                        int resposta = JOptionPane.showConfirmDialog(null, "Confirma a compra?\n "
                                + "(Após a confirmação, não será possivel\n a alteração e exclusão da venda)", "", JOptionPane.YES_NO_OPTION);

                        if (resposta == JOptionPane.YES_OPTION) {

                            String inseriItemVenda = "insert into item_venda(fk_num_venda, fk_cod_instrumento, qtd_venda, nome_cli) "
                                    + "values(last_insert_id()," + cod_instrumento + "," + jTextField9.getText() + ", '" + jTextField3.getText() + "');";
                            st.executeUpdate(inseriItemVenda);

                            String atualizaProduto = "update produto set qtd = qtd - " + jTextField9.getText() + " where cod_instrumento=" + cod_instrumento;
                            st.executeUpdate(atualizaProduto);

                            JOptionPane.showMessageDialog(null, "Item adicionado a venda");

                        } else {
                            JOptionPane.showMessageDialog(null, "Item não adicionado a venda!");
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "A quantidade excedeu o estoque disponível");

                    }

                } else if (qtd_estoque <= 0) {
                    JOptionPane.showMessageDialog(null, "Não há o produto no estoque!");
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registre a primeira compra para adicionar outros produtos a venda");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        //Aparecer dados na tabela depois de colocar a quantidade
        double valor_venda;
        int qtd_venda;
        valor_venda = Double.valueOf(jTextField11.getText()); //Integer.parseInt(jTextField11.getText());
        qtd_venda = Integer.valueOf(jTextField9.getText());
        table2 = (DefaultTableModel) jTable2.getModel();
        table2.setRowCount(0); //limpa toda a tabela e deixa vazia

        Object[] dados = {jTextField2.getText(), jTextField6.getText(), jTextField11.getText(), jTextField9.getText(), (valor_venda * qtd_venda), (valor_venda * qtd_venda)};
        table2.addRow(dados);

    }//GEN-LAST:event_jTextField9FocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Retornar a principal:
        TelaPrincipalMB principal = new TelaPrincipalMB();

        principal.setVisible(true); // retorna a tela principal

        dispose(); // fecha este formulário e retorna ao formulário anterior.
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        //A combobox de tipo fica dependente da combobox de categoria:
        if (jComboBox2.getSelectedItem().equals("Áudio Profissional")) {

            jComboBox3.removeAllItems();
            jComboBox2.setSelectedItem("Audio Profissional");

            jComboBox3.addItem("Selecione o tipo");
            jComboBox3.addItem("Acessórios");
            jComboBox3.addItem("Cabos");
            jComboBox3.addItem("Caixas Acusticas");
            jComboBox3.addItem("Fones de Ouvido");
            jComboBox3.addItem("Microfones");
            jComboBox3.addItem("Mixers e Mesas");
            jComboBox3.addItem("Processadores");
            jComboBox3.addItem("Sistema sem Fio");
            jComboBox3.addItem("Tecnologia");

        } else if (jComboBox2.getSelectedItem().equals("Bateria & Percussão")) {

            jComboBox3.removeAllItems();
            jComboBox2.setSelectedItem("Bateria & Percussão");

            jComboBox3.addItem("Selecione o tipo");
            jComboBox3.addItem("Acessórios");
            jComboBox3.addItem("Bateria Acústica");
            jComboBox3.addItem("Bateria Eletrônica");
            jComboBox3.addItem("Ferragens");
            jComboBox3.addItem("Peles");
            jComboBox3.addItem("Percussão");
            jComboBox3.addItem("Kit de Pratos");

        } else if (jComboBox2.getSelectedItem().equals("Cordas & Acessórios")) {

            jComboBox3.removeAllItems();
            jComboBox2.setSelectedItem("Cordas & Acessórios");

            jComboBox3.addItem("Selecione o tipo");
            jComboBox3.addItem("Acessórios");
            jComboBox3.addItem("Amplificadores para Baixo");
            jComboBox3.addItem("Amplificadores para Guitarra");
            jComboBox3.addItem("Bandolim");
            jComboBox3.addItem("Cases");
            jComboBox3.addItem("Cavaco & Banjo");
            jComboBox3.addItem("Contrabaixo");
            jComboBox3.addItem("Controladores & Footswitch");
            jComboBox3.addItem("Efeitos");
            jComboBox3.addItem("Encordoamento");
            jComboBox3.addItem("Guitarra");
            jComboBox3.addItem("Palhetas e Dedeiras");
            jComboBox3.addItem("Peças e Reposições");
            jComboBox3.addItem("Pedal de efeito");
            jComboBox3.addItem("Pedaleira & Multi Efeito");
            jComboBox3.addItem("Ukulele");
            jComboBox3.addItem("Viola Caipira");
            jComboBox3.addItem("Violão Acústico");
            jComboBox3.addItem("Violão Eletroacústico");
            jComboBox3.addItem("Violino");
            jComboBox3.addItem("Violoncello");
        } else if (jComboBox2.getSelectedItem().equals("Pianos & Teclados")) {

            jComboBox3.removeAllItems();
            jComboBox2.setSelectedItem("Pianos & Teclados");

            jComboBox3.addItem("Selecione o tipo");
            jComboBox3.addItem("Acessórios");
            jComboBox3.addItem("Acordeons");
            jComboBox3.addItem("Amplificadores");
            jComboBox3.addItem("Arranjadores");
            jComboBox3.addItem("Controladores");
            jComboBox3.addItem("Pianos");
            jComboBox3.addItem("Synths");
            jComboBox3.addItem("Teclados");
            jComboBox3.addItem("WorkStations");

        } else if (jComboBox2.getSelectedItem().equals("Sopro")) {

            jComboBox3.removeAllItems();
            jComboBox2.setSelectedItem("Sopro");

            jComboBox3.addItem("Selecione o tipo");
            jComboBox3.addItem("Acessórios");
            jComboBox3.addItem("Clarinetas");
            jComboBox3.addItem("Flautas");
            jComboBox3.addItem("Gaitas");
            jComboBox3.addItem("Geral");
            jComboBox3.addItem("Saxofone");
            jComboBox3.addItem("Trompete");

        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // coloca o nome do cliente quando escrito o cpf/cnpj:

        try {
            String pesquisaCliente = "Select nome from cliente where cpf_cnpj= '" + jTextField1.getText() + "'";
            resultado = st.executeQuery(pesquisaCliente); // executa a variavel com os comandos do BD
            if (resultado.next()) { // se tiver valor
                jTextField3.setText(resultado.getString("nome"));
            } else {

            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Adiciona venda no banco de dados:
        try {

            String fk_cpf_cnpj, nome_cli, categoria, tp_instrumento, nome_instrumento, marca, cor, forma_pagamento;
            int cod_instrumento, qtd_venda;
            double valor_venda, valor_total;

            fk_cpf_cnpj = jTextField1.getText();
            cod_instrumento = Integer.valueOf(jTextField2.getText());// Integer.parseInt(jTextField2.getText());
            nome_cli = jTextField3.getText();
            categoria = (String) jComboBox2.getSelectedItem();
            tp_instrumento = (String) jComboBox3.getSelectedItem();
            nome_instrumento = jTextField6.getText();
            marca = (String) jComboBox4.getSelectedItem();
            cor = (String) jComboBox5.getSelectedItem();
            valor_venda = Double.valueOf(jTextField11.getText()); //Integer.parseInt(jTextField11.getText()); //usar getString depois
            qtd_venda = Integer.valueOf(jTextField9.getText());
            forma_pagamento = (String) jComboBox6.getSelectedItem();
            valor_total = valor_venda * qtd_venda;

            String selecionaQtd = "select qtd from produto where cod_instrumento= " + cod_instrumento + ";";
            resultado = st.executeQuery(selecionaQtd);

            if (resultado.next()) {
                String qtdProduto = resultado.getString("qtd");

                int qtd_estoque = Integer.valueOf(qtdProduto);
                int qtd_ProdutoVenda = Integer.valueOf(jTextField9.getText());

                if (qtd_estoque > 0) {
                    if (qtd_ProdutoVenda <= qtd_estoque) {

                        int resposta = JOptionPane.showConfirmDialog(null, "Confirma a compra?\n "
                                + "(Após a confirmação, não será possivel\n a alteração e exclusão da venda)", "", JOptionPane.YES_NO_OPTION);
                        if (resposta == JOptionPane.YES_OPTION) {

                            String inseriVenda = "insert into venda(fk_cpf_cnpj, nome_cli, cod_instrumento, categoria, tp_instrumento,"
                                    + " nome_instrumento, marca, cor, valor_venda, qtd_venda, subtotal, valor_total, forma_pagamento, data_hora) values('"
                                    + fk_cpf_cnpj + "','" + nome_cli + "'," + cod_instrumento + ",'" + categoria + "','" + tp_instrumento + "','" + nome_instrumento
                                    + "','" + marca + "','" + cor + "'," + valor_venda + "," + qtd_venda + "," + valor_total + "," + valor_total + ",'" + forma_pagamento
                                    + "', now());";
                            st.executeUpdate(inseriVenda);

                            String inseriItemVenda = "insert into item_venda(fk_num_venda, fk_cod_instrumento, qtd_venda, nome_cli) values(last_insert_id(),"
                                    + jTextField2.getText() + "," + jTextField9.getText() + ", '" + jTextField3.getText() + "');";
                            st.executeUpdate(inseriItemVenda);

                            String atualizaProduto = "update produto set qtd = qtd - " + qtd_venda + " where cod_instrumento=" + cod_instrumento;
                            st.executeUpdate(atualizaProduto);

                            JOptionPane.showMessageDialog(null, "Venda efetuada com sucesso!");

                        } else {
                            JOptionPane.showMessageDialog(null, "Venda Cancelada!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "A quantidade excedeu o estoque disponível");

                    }

                } else if (qtd_estoque <= 0) {
                    JOptionPane.showMessageDialog(null, "Não há o produto no estoque!");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos não estão preenchidos!");

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Limpa todos os campos:

        limpaDados();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // pesquisa sobre a venda e mostra os dados na tabela:
        try {

            String pesquisaVenda = "SELECT produto.cod_instrumento, produto.nome, produto.valor_venda, item_venda.qtd_venda, (produto.valor_venda*item_venda.qtd_venda) as subtotal\n"
                    + "FROM item_venda\n"
                    + "INNER JOIN produto ON (item_venda.fk_cod_instrumento = produto.cod_instrumento) where nome_cli='" + jTextField3.getText() + "';";
            resultado = st.executeQuery(pesquisaVenda); // executa a variavel com os comandos do BD

            while (resultado.next()) { // se tiver valor
                // JOptionPane.showMessageDialog(null, "Venda encontrada"); // chama este import para aparecer uma mensagem

                table2 = (DefaultTableModel) jTable2.getModel();
                Object[] dados = {resultado.getString("produto.cod_instrumento"), resultado.getString("produto.nome"), resultado.getString("produto.valor_venda"),
                    resultado.getString("item_venda.qtd_venda"), resultado.getString("subtotal"), resultado.getString("subtotal")};
                table2.addRow(dados);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseEntered

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // coloca os dados do produto depois de escrito o código do produto:

        try {

            String pesquisaProduto = "Select nome,categoria, tp_instrumento,marca, cor, valor_venda from produto where cod_instrumento=" + jTextField2.getText();
            resultado = st.executeQuery(pesquisaProduto); // executa a variavel com os comandos do BD
            if (resultado.next()) { // se tiver valor
                jTextField6.setText(resultado.getString("nome"));
                jTextField11.setText(resultado.getString("valor_venda"));
                jComboBox2.setSelectedItem(resultado.getString("categoria"));
                jComboBox3.setSelectedItem(resultado.getString("tp_instrumento"));
                jComboBox4.setSelectedItem(resultado.getString("marca"));
                jComboBox5.setSelectedItem(resultado.getString("cor"));

            } else {
                JOptionPane.showMessageDialog(null, "código não encontrado");
            }

        } catch (Exception e) {

        }

    }//GEN-LAST:event_jTextField2FocusLost

    private void limpaDados() {

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox2.setSelectedItem("Selecione a categoria");
        jComboBox3.setSelectedItem("Selecione o tipo");
        jTextField6.setText("");
        jComboBox4.setSelectedItem("Selecione a marca");
        jComboBox5.setSelectedItem("Selecione a cor");
        jTextField9.setText("");
        jTextField11.setText("");
        jComboBox6.setSelectedItem("Selecione a forma de pagamento");

        table2 = (DefaultTableModel) jTable2.getModel();
        table2.setRowCount(0); //limpa toda a tabela e deixa vazia

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
